accounts/urls.py
from django.urls import path
from accounts.views import home, user_login

app_name = 'accounts'

urlpatterns = [
    path('', home, name='home'),
    path('login/', user_login, name='user_login'),
]

cms/urls.py
from django.contrib import admin
from django.urls import path, include  #, re_path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),   #re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('blogs/', include('blogs.urls')),
    path('coins/', include('coins.urls')),
]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_no = models.CharField(max_length=30, default='', blank=True)
    api_key = models.CharField(max_length=40, default='', blank=True)
    secret_no = models.CharField(max_length=40, default='', blank=True)

    def __str__(self):
        return self.user.username

accounts/views.py
from django.contrib.auth import authenticate, login
from django import forms
from django.http import HttpResponse
from django.shortcuts import render
from accounts.models import Profile
import requests

# API 位址  https://api.hitbtc.com/
# sample code ： https://github.com/hitbtc-com/hitbtc-api/blob/master/example_rest.py


class LoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)


# def home(request):
# #     my_profile = Profile.objects.get(user__username='guangyaw')
# #     session = requests.session()
# #     session.auth = (my_profile.api_key, my_profile.secret_no)
# #     b = session.get('https://api.hitbtc.com/api/2/trading/balance').json()
# #     mybalances = []
# #     for balances in b:
# #         if balances["available"] != '0':
# #             mybalances.append(balances)
# #
# #     return render(request, "accounts/accounts_home.html", {"balance": mybalances, "title": 'test balance'})

def home(request):
    return HttpResponse('account home')


def user_login(request):
    if request.method == 'POST':
        login_form = LoginForm(request.POST)
        if login_form.is_valid():
            tmp = login_form.cleaned_data
            user = authenticate(username=tmp['username'], password=tmp['password'])
            if user:
                login(request, user)
                return HttpResponse('login successfully')
            else:
                return HttpResponse('login failed')
        else:
            return HttpResponse('invalid login')

    if request.method == 'GET':
        login_form = LoginForm()
        return render(request, 'accounts/login.html', {'form': login_form})

templates/accounts/accounts_home.html
{% extends "base.html" %}

{% block meta_block %}
{% endblock %}

{% block title_block %}
    {{title}}
{% endblock %}

{% block body_block %}
    <div>{{ balance }}</div>
{% endblock %}

templates/accounts/login.html
{% extends "base.html" %}

{% block title_block %}
    Login
{% endblock title_block %}

{% block body_block %}
    <div class="row text-center vertical-middle-sm">
    <h1>Login</h1>
        <form method="post" action=".">
        {% csrf_token %}
            {{ form.as_p }}
{#            <table>#}
{#            <tr>#}
{#                <td>{{ form.username.label_tag }}</td>#}
{#                <td>{{ form.username }}</td>#}
{#            </tr>#}
{#            <tr>#}
{#                <td>{{ form.password.label_tag }}</td>#}
{#                <td>{{ form.password }}</td>#}
{#            </tr>#}
{#            </table>#}
            <input type="submit" value="login">
        </form>
    </div>
{% endblock body_block %}

templates/accounts/logout.html
{% extends "base.html" %}

{% block title_block %}
    Logout
{% endblock title_block %}

{% block body_block %}
    <div class="row text-center vertical-middle-sm">
    <p>You have logout</p>
    <p>You can <a href="{% url 'accounts:user_login' %}">Login</a> again </p>
    </div>
{% endblock body_block %}